-- Ejecuta este script en Supabase SQL Editor antes de iniciar la app.

create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    status text not null default 'Pendiente' check (status in ('Pendiente', 'En progreso', 'Completada')),
    priority text not null default 'Media' check (priority in ('Baja', 'Media', 'Alta')),
    created_at timestamptz not null default now()
);

-- Para una práctica sencilla, se habilita RLS y se permite acceso anónimo controlado.
-- En producción se recomienda usar autenticación real por usuario.
alter table public.tasks enable row level security;

drop policy if exists "anon_select_tasks" on public.tasks;
create policy "anon_select_tasks"
on public.tasks for select
to anon
using (true);

drop policy if exists "anon_insert_tasks" on public.tasks;
create policy "anon_insert_tasks"
on public.tasks for insert
to anon
with check (true);

drop policy if exists "anon_update_tasks" on public.tasks;
create policy "anon_update_tasks"
on public.tasks for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_tasks" on public.tasks;
create policy "anon_delete_tasks"
on public.tasks for delete
to anon
using (true);
